apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes-db
  name: oes-db
spec:
  type: ClusterIP
  ports:
  - name: oes-db
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: oes-db
