apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    component: ldap
  name: oes-ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes-ldap
  strategy: {}
  template:
    metadata:
      labels:
        app: oes-ldap
    spec:
      containers:
      - image: skandragon/ldap-testing-db:latest
        ports:
        - containerPort: 3389
          protocol: TCP
        name: oes-ldap
        resources: {}
