apiVersion: v1
data:
  # Init container will automatically replace OES_GATE_IP string with LoadBalancer
  # IP of oes-gate service; Needn't modify this
  app-config.json: |
    {
        "endPointUrl":"http://OES_GATE_IP:8084/"
    }

kind: ConfigMap
metadata:
  name: oes-ui-config
