apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: oes-ui
  name: oes-ui
spec:
  type: LoadBalancer
  ports:
  - name: "oes-ui-service"
    port: 80
    targetPort: 80
  selector:
    app: oes
    component: oes-ui
