apiVersion: v1
data:
  gate.yml: |
    services:
      opsmx:
        baseUrl: http://oes-sapor:8085
        enabled: true
      autopilot:
        baseUrl: http://autopilot:8090
        enabled: true
      platform:
        baseUrl: http://oes-platform:8095
        userGroupApiPath: /platformservice/v1/users/{username}/usergroups/importAndCache
        enabled: true
      dashboard:
        baseUrl: http://oes-dashboard:8094
        enabled: true
    security:
      basic:
        enabled: true
      user: {}
    cors:
      allowed-origins-pattern: ^https?://(?:localhost|OES_UI_LOADBALANCER_IP|opsmx.com)(?::[1-9]\d*)?/?
    ldap:
      enabled: true
      url: ldap://oes-ldap:9595/DC=example,DC=com
      userDnPattern: uid={0},ou=Users
    file:
      enabled: false
      url: /platformservice/v1/users/authenticate
    authn:
      mode: session
    google: {}
    logging:
      level:
        com.netflix.spinnaker.gate.security: DEBUG
        org.springframework.security: DEBUG
        org.springframework.web: DEBUG
    redis:
      connection: redis://redis-master:6379

kind: ConfigMap
metadata:
  name: oes-gate-config
