apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    component: oes-gate
  name: oes-gate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: oes-gate
  template:
    metadata:
      labels:
        app: oes
        component: oes-gate
    spec:
      initContainers:
      - env:
        - name: EXTERNAL_IP_CHECK_DELAY
          value: "120"
        - name: SPINNAKER_SETUP_DELAY
          value: "10"
        image: opsmx11/oes-init:v2
        imagePullPolicy: Always
        name: oes-gate-init
        command: ["/home/config_endpoint.sh"]
        args: ["oes-gate"]
        volumeMounts:
        - mountPath: /config
          name: config-temp
        - mountPath: /opt/spinnaker/config
          name: gate-volume
      containers:
      - image: opsmx11/oes-gate:v0.202009101611
        name: oes-gate
        ports:
        - containerPort: 8084
          protocol: TCP
        volumeMounts:
        - name: gate-volume
          mountPath: /opt/spinnaker/config
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1500Mi"
            cpu: "1500m"
        readinessProbe:
          tcpSocket:
            port: 8084
          initialDelaySeconds: 120
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 300
          periodSeconds: 60
      imagePullSecrets:
      - name: opsmx11-secret
      volumes:
      - configMap:
          name: oes-gate-config
        name: config-temp
      - emptyDir: {}
        name: gate-volume
