apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: oes-gate
  name: oes-gate
spec:
  type: LoadBalancer
  ports:
  - name: "oes-gate-service"
    port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: oes
    component: oes-gate
