apiVersion: v1
data:
  audit.yml: |
    services:
      audit:
        applicationRefreshIntervalMs: 50000
  oes.yml: |
    server:
      port: 8085
      compression:
        enabled: true
    feign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
        platformservice:
          name: platformservice
          url: http://oes-platform:8095/
  persistence.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://db-opsmx:5432/oesdb
        username: postgres
        password: networks123
        driver-class-name: org.postgresql.Driver
        testWhileIdle: true
        test-on-borrow: true
        hikari:
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1000
          maxLifetime: 1800000
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: update # delete this property after table creation
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

    logging:
      level:
        com:
          zaxxer:
            hikari: DEBUG
  spinnaker.yaml: |
    spinnaker:
      base-url: http://40.64.77.192:9000/gate
      external-base-url: http://40.64.77.192:9000/gate
      username: admin
      password: OpsMx@123
      adminLoginEnabled: false
      adminUsername:
      adminPassword:
      authnEnabled: false

  charts.yml: |
    charts:
      - chart:
          id: 1
          name: Pipeline Status
          displayName: Pipeline Status
          timeExists: false
          type: stacket-horizontal-bar-chart
          showGridLines: true
          showXAxisLabel: true
          showYAxisLabel: true
          tooltipDisabled: true
          xAxis:
            name: count
            label: count
            unit: count
          yAxis:
            name: pipelines
            label: pipelines
            unit: pipelines
      - chart:
          id: 2
          name: Successful Pipelines
          displayName: Successful Pipelines
          timeExists: false
          type: horizontal-bar-chart
          showGridLines: true
          showXAxisLabel: true
          showYAxisLabel: true
          tooltipDisabled: true
          colorScheme:
            domain:
              - "#33b3f1"
          xAxis:
            name: count
            label: count
            unit: count
          yAxis:
            name: pipelines
            label: pipelines
            unit: pipelines
      - chart:
          id: 3
          name: Failed Pipelines
          displayName: Failed Pipelines
          type: horizontal-bar-chart
          timeExists: false
          showGridLines: true
          showXAxisLabel: true
          showYAxisLabel: true
          tooltipDisabled: true
          colorScheme:
            domain:
              - "#33b3f1"
          xAxis:
            name: count
            label: count
            unit: count
          yAxis:
            name: pipelines
            label: pipelines
            unit: pipelines
      - chart:
          id: 4
          name: Fastest Pipelines
          displayName: Fastest Pipelines
          type: horizontal-bar-chart
          timeExists: true
          showGridLines: true
          showXAxisLabel: true
          showYAxisLabel: true
          tooltipDisabled: true
          colorScheme:
            domain:
              - "#33b3f1"
          xAxis:
            name: time
            label: time
            unit: time
          yAxis:
            name: pipelines
            label: pipelines
            unit: pipelines
      - chart:
          id: 5
          name: Slowest Pipelines
          displayName: Slowest Pipelines
          type: horizontal-bar-chart
          timeExists: true
          showXAxisLabel: true
          showYAxisLabel: true
          tooltipDisabled: true
          gradient: true
          colorScheme:
            domain:
              - "#33b3f1"
          xAxis:
            name: time
            label: time
            unit: time
          yAxis:
            name: pipelines
            label: pipelines
            unit: pipelines
      - chart:
          id: 6
          name: Automated Verification
          displayName: Automated Verification
          type: horizontal-bar-chart
          showGridLines: true
          showXAxisLabel: true
          showYAxisLabel: true
          tooltipDisabled: true
          animations: true
          timeExists: false
          colorScheme:
            domain:
              - "#33b3f1"
          xAxis:
            name: count
            label: count
            unit: count
          yAxis:
            name: stage
            label: stage
            unit: stage
      - chart:
          id: 7
          name: Manual Judgement Time
          displayName: Manual Judgement Time
          showXAxisLabel: true
          showYAxisLabel: true
          tooltipDisabled: true
          animations: true
          showGridLines: true
          type: horizontal-bar-chart
          timeExists: true
          colorScheme:
            domain:
              - "#33b3f1"
          xAxis:
            name: time
            label: time
            unit: time
          yAxis:
            name: pipelines
            label: pipelines
            unit: pipelines
      - chart:
          id: 8
          name: Rollback Services
          displayName: Rollback Services
          showXAxisLabel: true
          showYAxisLabel: true
          tooltipDisabled: true
          animations: true
          showGridLines: true
          type: pie-chart
          timeExists: false
          colorScheme:
            domain:
              - "#33b3f1"
          xAxis:
            name: count
            label: count
            unit: count
          yAxis:
            name: pipelines
            label: pipelines
            unit: pipelines
      - chart:
          id: 9
          name: Health Status
          displayName: Health Status
          showXAxisLabel: true
          showYAxisLabel: true
          tooltipDisabled: true
          animations: true
          showGridLines: true
          type: area-chart
          timeExists: true
          colorScheme:
            domain:
              - "#33b3f1"
          xAxis:
            name: time
            label: time
            unit: time
          yAxis:
            name: pipelines
            label: pipelines
            unit: pipelines

    filters:
      days:
        - 1
        - 7
        - 30

kind: ConfigMap
metadata:
  name: sapor-config
