apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    component: sapor
  name: sapor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: sapor
  template:
    metadata:
      labels:
        app: oes
        component: sapor
    spec:
      initContainers:
      - env:
        - name: EXTERNAL_IP_CHECK_DELAY
          value: "120"
        - name: SPINNAKER_SETUP_DELAY
          value: "10"
        image: opsmx11/oes-init:v2
        imagePullPolicy: Always
        name: sapor-init
        command: ["/home/config_endpoint.sh"]
        args: ["sapor"]
        volumeMounts:
        - mountPath: /config
          name: config-temp
        - mountPath: /opt/opsmx/
          name: api-volume
      containers:
      - image: opsmx11/sapor:v0.202009031851
        name: sapor
        ports:
        - containerPort: 8085
          protocol: TCP
        volumeMounts:
        - name: api-volume
          mountPath: /opt/opsmx/
        readinessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 120
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 180
          periodSeconds: 60
      imagePullSecrets:
      - name: opsmx11-secret
      volumes:
      - configMap:
          name: sapor-config
        name: config-temp
      - emptyDir: {}
        name: api-volume
