apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db-opsmx
  name: db-opsmx
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  serviceName: db-opsmx
  selector:
    matchLabels:
      app: db-opsmx
  template:
    metadata:
      labels:
        app: db-opsmx
    spec:
      imagePullSecrets:
        - name: opsmx11-secret
      containers:
      - image: opsmxdev/ubi8-autopilot-db:v1.5
        imagePullPolicy: IfNotPresent
        name: db-opsmx
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/lib/pgsql-pv"
          name: db-opsmx-postgresql
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10
          periodSeconds: 5
      securityContext:
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      labels:
        app: db-opsmx
      name: db-opsmx-postgresql
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      volumeMode: Filesystem
