apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes-platform
  name: oes-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes-platform
  strategy: {}
  template:
    metadata:
      labels:
        app: oes-platform
    spec:
      containers:
      - image: opsmx11/platform-service:master-202009031321
        name: platform-service
        ports:
        - containerPort: 8095
          protocol: TCP
        env:
        - name: CONF_DIR
          value: /opsmx/conf/
        volumeMounts:
        - mountPath: /opsmx/conf/application.yml
          name: platform-config
          subPath: application.yml
        - mountPath: /opsmx/conf/userGroups.yml
          name: platform-config
          subPath: userGroups.yml
        - mountPath: /opsmx/conf/users.yml
          name: platform-config
          subPath: users.yml
        readinessProbe:
          tcpSocket:
            port: 8095
          initialDelaySeconds: 120
          periodSeconds: 10
      imagePullSecrets:
      - name: opsmx11-secret
      volumes:
      - name: platform-config
        configMap:
          name: oes-platform-config
