apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes-platform
  name: oes-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes-platform
  strategy: {}
  template:
    metadata:
      labels:
        app: oes-platform
    spec:
      initContainers:
      - name: init-mydb
        image: busybox:1.28
        command: ['sh', '-c', "sleep 30;until nslookup oes-db.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for db-opsmx to be up and running; sleep 2; done"]
      containers:
      - image: opsmx11/platform-service:master-202009110803
        name: platform-service
        ports:
        - containerPort: 8095
          protocol: TCP
        env:
        - name: CONF_DIR
          value: /opsmx/conf/
        volumeMounts:
        - mountPath: /opsmx/conf/platform.yml
          name: platform-config
          subPath: platform.yml
        readinessProbe:
          tcpSocket:
            port: 8095
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /mgmt/health
            port: 8095
          initialDelaySeconds: 60
          periodSeconds: 60
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1500Mi"
            cpu: "1500m"
      imagePullSecrets:
      - name: opsmx11-secret
      volumes:
      - name: platform-config
        configMap:
          name: oes-platform-config
