apiVersion: v1
data:
  application.yml: |
    spring:
      profiles: local
      datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
          connection-timeout: 5000
          idleTimeout: 300000
          maxLifetime: 600000
          minimumIdle: 3
          maximumPoolSize: 5
        test-on-borrow: true
        testWhileIdle: true
        url: jdbc:postgresql://db-opsmx:5432/platformdb
        username: postgres
        password: networks123
      jpa:
        hibernate:
          ddl-auto: update
        propertieshibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    name: Platform-Service
    rbacEnabled: true
    userGroup:
      cache: inMemory
      adminGroups: admin, admin1
    user:
      source: file
    ---

    spring:
      profiles: dev
      datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
          connectionTimeout: 5000
          idleTimeout: 300000
          maxLifetime: 600000
          minimumIdle: 3
          maximumPoolSize: 5
        test-on-borrow: true
        testWhileIdle: true
        url: jdbc:postgresql://db-opsmx:5432/platformdb
        username: postgres
        password: networks123
      jpa:
        hibernate:
          ddl-auto: update
        propertieshibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    name: Platform-Service
    rbacEnabled: true
    userGroup:
      cache: inMemory
      adminGroups: admin, admin1
    user:
      source: file
    ---

    spring:
      profiles: test
      datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
          connectionTimeout: 5000
          idleTimeout: 300000
          maxLifetime: 600000
          minimumIdle: 3
          maximumPoolSize: 5
        test-on-borrow: true
        testWhileIdle: true
        url: jdbc:postgresql://db-opsmx:5432/platformdb
        username: postgres
        password: networks123
      jpa:
        hibernate:
          ddl-auto: create-drop
        propertieshibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    name: Platform-Service
    rbacEnabled: true
    userGroup:
      cache: redis
      adminGroups: Administrators
    user:
      source: ldap
    ldap:
      adminDn: cn=admin,dc=example,dc=com
      adminPassword: adminroot123
      baseDn: dc=example,dc=com
      url: ldap://oes-ldap:9595
      userDisplayName: displayName
      userFilterPattern: (&(uid=USERNAME))
      userGroupIdentity: memberOf
      userIdentity: cn
      userPrepend: uid=USERNAME,ou=Users
    redis:
      hostname: redis-master
      port: 6379
    ---

    spring:
      profiles: uat
      datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
          connectionTimeout: 5000
          idleTimeout: 300000
          maxLifetime: 600000
          minimumIdle: 3
          maximumPoolSize: 5
        test-on-borrow: true
        testWhileIdle: true
        url: jdbc:postgresql://db-opsmx:5432/platformdb
        username: postgres
        password: networks123
      jpa:
        hibernate:
          ddl-auto: update
        propertieshibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    name: Platform-Service
    rbacEnabled: true
    userGroup:
      cache: redis
      adminGroups: admin, admin1
    user:
      source: ldap
    ldap:
      adminDn: cn=admin,dc=example,dc=com
      adminPassword: adminroot123
      baseDn: dc=example,dc=com
      url: ldap://oes-ldap:9595
      userDisplayName: displayName
      userFilterPattern: (&(uid=USERNAME))
      userGroupIdentity: memberOf
      userIdentity: cn
      userPrepend: uid=USERNAME,ou=Users
  userGroups.yml: |
    userGroups:
      - name: group1
        users:
          - user1
          - user2
      - name: group2
        users:
          - user2
          - user3
          - user4
      - name: admin
        users:
          - user5
          - user7
      - name: admin1
        users:
          - user6
          - user7
  users.yml: |
    users:
      - username: user1
        password: user1p
      - username: user2
        password: user2p
      - username: user3
        password: user3p
      - username: user4
        password: user4p
      - username: user5
        password: user5p
      - username: user6
        password: user6p
      - username: user7
        password: user7p
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"application.yml":"spring:\n  profiles: local\n  datasource:\n    driver-class-name: org.postgresql.Driver\n    hikari:\n      connection-timeout: 5000\n      idleTimeout: 300000\n      maxLifetime: 600000\n      minimumIdle: 3\n      maximumPoolSize: 5\n    test-on-borrow: true\n    testWhileIdle: true\n    url: jdbc:postgresql://db-opsmx:5432/platformdb\n    username: postgres\n    password: networks123\n  jpa:\n    hibernate:\n      ddl-auto: update\n    propertieshibernate:\n      dialect: org.hibernate.dialect.PostgreSQLDialect\n    show-sql: true\nname: Platform-Service\nrbacEnabled: true\nuserGroup:\n  cache: inMemory\n  adminGroups: admin, admin1\nuser:\n  source: file\n---\n\nspring:\n  profiles: dev\n  datasource:\n    driver-class-name: org.postgresql.Driver\n    hikari:\n      connectionTimeout: 5000\n      idleTimeout: 300000\n      maxLifetime: 600000\n      minimumIdle: 3\n      maximumPoolSize: 5\n    test-on-borrow: true\n    testWhileIdle: true\n    url: jdbc:postgresql://db-opsmx:5432/platformdb\n    username: postgres\n    password: networks123\n  jpa:\n    hibernate:\n      ddl-auto: update\n    propertieshibernate:\n      dialect: org.hibernate.dialect.PostgreSQLDialect\n    show-sql: true\nname: Platform-Service\nrbacEnabled: true\nuserGroup:\n  cache: inMemory\n  adminGroups: admin, admin1\nuser:\n  source: file\n---\n\nspring:\n  profiles: test\n  datasource:\n    driver-class-name: org.postgresql.Driver\n    hikari:\n      connectionTimeout: 5000\n      idleTimeout: 300000\n      maxLifetime: 600000\n      minimumIdle: 3\n      maximumPoolSize: 5\n    test-on-borrow: true\n    testWhileIdle: true\n    url: jdbc:postgresql://db-opsmx:5432/platformdb\n    username: postgres\n    password: networks123\n  jpa:\n    hibernate:\n      ddl-auto: create-drop\n    propertieshibernate:\n      dialect: org.hibernate.dialect.PostgreSQLDialect\n    show-sql: true\nname: Platform-Service\nrbacEnabled: true\nuserGroup:\n  cache: redis\n  adminGroups: Administrators\nuser:\n  source: ldap\nldap:\n  adminDn: cn=admin,dc=example,dc=com\n  adminPassword: adminroot123\n  baseDn: dc=example,dc=com\n  url: ldap://oes-ldap:9595\n  userDisplayName: displayName\n  userFilterPattern: (\u0026(uid=USERNAME))\n  userGroupIdentity: memberOf\n  userIdentity: cn\n  userPrepend: uid=USERNAME,ou=Users\nredis:\n  hostname: redis-master\n  port: 6379\n---\n\nspring:\n  profiles: uat\n  datasource:\n    driver-class-name: org.postgresql.Driver\n    hikari:\n      connectionTimeout: 5000\n      idleTimeout: 300000\n      maxLifetime: 600000\n      minimumIdle: 3\n      maximumPoolSize: 5\n    test-on-borrow: true\n    testWhileIdle: true\n    url: jdbc:postgresql://db-opsmx:5432/platformdb\n    username: postgres\n    password: networks123\n  jpa:\n    hibernate:\n      ddl-auto: update\n    propertieshibernate:\n      dialect: org.hibernate.dialect.PostgreSQLDialect\n    show-sql: true\nname: Platform-Service\nrbacEnabled: true\nuserGroup:\n  cache: redis\n  adminGroups: admin, admin1\nuser:\n  source: ldap\nldap:\n  adminDn: cn=admin,dc=example,dc=com\n  adminPassword: adminroot123\n  baseDn: dc=example,dc=com\n  url: ldap://oes-ldap:9595\n  userDisplayName: displayName\n  userFilterPattern: (\u0026(uid=USERNAME))\n  userGroupIdentity: memberOf\n  userIdentity: cn\n  userPrepend: uid=USERNAME,ou=Users\n","userGroups.yml":"userGroups:\n  - name: group1\n    users:\n      - user1\n      - user2\n  - name: group2\n    users:\n      - user2\n      - user3\n      - user4\n  - name: admin\n    users:\n      - user5\n      - user7\n  - name: admin1\n    users:\n      - user6\n      - user7\n","users.yml":"users:\n  - username: user1\n    password: user1p\n  - username: user2\n    password: user2p\n  - username: user3\n    password: user3p\n  - username: user4\n    password: user4p\n  - username: user5\n    password: user5p\n  - username: user6\n    password: user6p\n  - username: user7\n    password: user7p\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"oes-platform-config","namespace":"oes-test3"}}
  creationTimestamp: "2020-09-07T11:21:19Z"
  name: oes-platform-config
  namespace: oes-test3
  resourceVersion: "54822808"
  selfLink: /api/v1/namespaces/oes-test3/configmaps/oes-platform-config
  uid: ec93d07e-9e8d-42d1-af61-07291c7c9ede
