apiVersion: v1
data:
  application.yml: |
    spring:
      profiles: local
      datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
          connection-timeout: 5000
          idleTimeout: 300000
          maxLifetime: 600000
          minimumIdle: 3
          maximumPoolSize: 5
        test-on-borrow: true
        testWhileIdle: true
        url: jdbc:postgresql://db-opsmx:5432/platformdb
        username: postgres
        password: networks123
      jpa:
        hibernate:
          ddl-auto: update
        propertieshibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    name: Platform-Service
    rbacEnabled: true
    userGroup:
      cache: inMemory
      adminGroups: admin, admin1
    user:
      source: file
    ---

    spring:
      profiles: dev
      datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
          connectionTimeout: 5000
          idleTimeout: 300000
          maxLifetime: 600000
          minimumIdle: 3
          maximumPoolSize: 5
        test-on-borrow: true
        testWhileIdle: true
        url: jdbc:postgresql://db-opsmx:5432/platformdb
        username: postgres
        password: networks123
      jpa:
        hibernate:
          ddl-auto: update
        propertieshibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    name: Platform-Service
    rbacEnabled: true
    userGroup:
      cache: inMemory
      adminGroups: admin, admin1
    user:
      source: file
    ---

    spring:
      profiles: test
      datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
          connectionTimeout: 5000
          idleTimeout: 300000
          maxLifetime: 600000
          minimumIdle: 3
          maximumPoolSize: 5
        test-on-borrow: true
        testWhileIdle: true
        url: jdbc:postgresql://db-opsmx:5432/platformdb
        username: postgres
        password: networks123
      jpa:
        hibernate:
          ddl-auto: update
        propertieshibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    name: Platform-Service
    rbacEnabled: true
    userGroup:
      cache: redis
      adminGroups: admin, admin1
    user:
      source: ldap
    ldap:
      adminDn: cn=admin,dc=example,dc=com
      adminPassword: adminroot123
      baseDn: dc=example,dc=com
      url: ldap://oes-ldap:9595
      userDisplayName: displayName
      userFilterPattern: (&(uid=USERNAME))
      userGroupIdentity: memberOf
      userIdentity: cn
      userPrepend: uid=USERNAME,ou=Users
    redis:
      hostname: redis-master
      port: 6379
    ---

    spring:
      profiles: uat
      datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
          connectionTimeout: 5000
          idleTimeout: 300000
          maxLifetime: 600000
          minimumIdle: 3
          maximumPoolSize: 5
        test-on-borrow: true
        testWhileIdle: true
        url: jdbc:postgresql://db-opsmx:5432/platformdb
        username: postgres
        password: networks123
      jpa:
        hibernate:
          ddl-auto: update
        propertieshibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    name: Platform-Service
    rbacEnabled: true
    userGroup:
      cache: redis
      adminGroups: admin, admin1
    user:
      source: ldap
    ldap:
      adminDn: cn=admin,dc=example,dc=com
      adminPassword: adminroot123
      baseDn: dc=example,dc=com
      url: ldap://oes-ldap:9595
      userDisplayName: displayName
      userFilterPattern: (&(uid=USERNAME))
      userGroupIdentity: memberOf
      userIdentity: cn
      userPrepend: uid=USERNAME,ou=Users


  userGroups.yml: |
    userGroups:
      - name: group1
        users:
          - user1
          - user2
      - name: group2
        users:
          - user2
          - user3
          - user4
      - name: admin
        users:
          - user5
          - user7
      - name: admin1
        users:
          - user6
          - user7
  users.yml: |
    users:
      - username: user1
        password: user1p
      - username: user2
        password: user2p
      - username: user3
        password: user3p
      - username: user4
        password: user4p
      - username: user5
        password: user5p
      - username: user6
        password: user6p
      - username: user7
        password: user7p

kind: ConfigMap
metadata:
  name: oes-platform-config
