# oes-ui, oes-gate & sapor deployments have init containers that will automatically
# configure them. Init container require access to view LoadBalancer IPs of corresponding
# services, use this manifest to give necessary access to the init container
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oes-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: default
