apiVersion: apps/v1
kind: Deployment
metadata:
  name: oes-autopilot
  labels:
    app: oes-autopilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes-autopilot
  template:
    metadata:
      labels:
        app: oes-autopilot
    spec:
      volumes:
        - name: autopilot-config-volume
          configMap:
            name: oes-autopilot-config
      imagePullSecrets:
        - name: opsmx11-secret
      containers:
        - image: opsmx11/autopilot:master-202009090707
          imagePullPolicy: IfNotPresent
          name: oes-autopilot
          ports:
            - containerPort: 8090
              name: backend
              protocol: TCP
            - containerPort: 9090
              name: metricfetcher
              protocol: TCP
          volumeMounts:
          - name: autopilot-config-volume
            mountPath: /opt/opsmx/autopilot.properties
            subPath: autopilot.properties
          - name: autopilot-config-volume
            mountPath: /opt/opsmx/hibernate.cfg.xml
            subPath: hibernate.cfg.xml
          readinessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /mgmt/health
              port: 8090
            initialDelaySeconds: 120
            periodSeconds: 60
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "3500Mi"
              cpu: "1500m"
