apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: oes
    version: "3.0"
  name: oes-ui-ingress
spec:
  rules:
  - host: nightly-oes3.opsmx.com
    http:
      paths:
      - backend:
          serviceName: oes-ui
          servicePort: 80
        path: /
  tls:
  - hosts:
    - nightly-oes3.opsmx.com
    secretName: godaddy
status:
  loadBalancer:
    ingress:
    - ip: 40.90.217.183
