apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: oes
    version: "3.0"
  name: oes-ui-ingress
spec:
  rules:
  - host: <identifier>.engineering.opsmx.net
    http:
      paths:
      - backend:
          serviceName: oes-ui
          servicePort: 80
        path: /
