apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    component: oes-sapor
  name: oes-sapor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: oes-sapor
  template:
    metadata:
      labels:
        app: oes
        component: oes-sapor
    spec:
      containers:
      - image: opsmx11/sapor:v0.202009141117
        name: oes-sapor
        ports:
        - containerPort: 8085
          protocol: TCP
        volumeMounts:
        - name: sapor-config-volume
          mountPath: /opt/opsmx/application.yml
          subPath: application.yml
        readinessProbe:
          failureThreshold: 6
          tcpSocket:
            port: 8085
          initialDelaySeconds: 120
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 180
          periodSeconds: 60
        resources:
          requests:
            memory: "100Mi"
            cpu: "300m"
          limits:
            memory: "500Mi"
            cpu: "1500m"
      imagePullSecrets:
      - name: opsmx11-secret
      volumes:
      - configMap:
          name: oes-sapor-config
        name: sapor-config-volume
