apiVersion: apps/v1
kind: Deployment
metadata:
  name: autopilot
  labels:
    app: autopilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autopilot
  template:
    metadata:
      labels:
        app: autopilot
    spec:
      volumes:
        - name: backend-config-volume
          configMap:
            name: autopilotbackendconfig
      imagePullSecrets:
        - name: opsmx11-secret
      containers:
        - image: opsmx11/autopilot:master-202009081323
          imagePullPolicy: IfNotPresent
          name: autopilot
          ports:
            - containerPort: 8090
              name: backend
              protocol: TCP
            - containerPort: 9090
              name: metricfetcher
              protocol: TCP
          volumeMounts:
          - name: backend-config-volume
            mountPath: /opt/opsmx/application.properties
            subPath: application.properties
          - name: backend-config-volume
            mountPath: /opt/opsmx/hibernate.cfg.xml
            subPath: hibernate.cfg.xml
          readinessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /mgmt/health
              port: 8090
            initialDelaySeconds: 120
            periodSeconds: 60
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "3500Mi"
              cpu: "1500m"
