apiVersion: v1
kind: Service
metadata:
  labels:
    app: autopilot
  name: autopilot
spec:
  type: ClusterIP
  ports:
  - name: "cas-service"
    port: 8090
    targetPort: 8090
  - name: "monitoring-service"
    port: 9090
    targetPort: 9090
  selector:
    app: autopilot
